# common handlers that various roles can call

# variable controls version (@see common/vars)
- name: restart tomcat
  service: name={{tomcat}} state=restarted

- name: restart apache
  service: name={{apache}} state=restarted
